nodeLinker: node-modules

packageExtensions:
  "debug@*":
    peerDependenciesMeta:
      "supports-color":
        optional: true
  "@nrwl/detox@15.9.2":
    peerDependencies:
      nx: 15.9.2
      typescript: ^4
  "@nrwl/jest@15.9.2":
    peerDependencies:
      nx: 15.9.2
      typescript: ^4
  "@nrwl/js@15.9.2":
    peerDependencies:
      nx: 15.9.2
      typescript: ^4
  "@nrwl/linter@15.9.2":
    peerDependencies:
      nx: 15.9.2
      typescript: ^4
  "@nrwl/react-native@15.9.2":
    peerDependencies:
      nx: 15.9.2
      typescript: ^4
    peerDependenciesMeta:
      detox:
        optional: true
  "@nrwl/react@15.9.2":
    peerDependencies:
      nx: 15.9.2
      typescript: ^4
    peerDependenciesMeta:
      webpack:
        optional: true
  react-native-codegen@^0.71.5:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  react-native@0.71.7:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  styled-components@5.3.9:
    peerDependenciesMeta:
      react-dom:
        optional: true
      react-is:
        optional: true
